### ISSUE TITLE
Individual level SV genotype data

### ISSUE THREAD

**Issue by tingqi** [RajLabMSSM/AMP_AD_StructuralVariation#1]
Dear Team,

Thanks for sharing the sv-xQTLs. I am wondering how I can get access to the individual-level SV genotype data. 

It says that "Individual-level genotyping can be found at [Synapse:syn26952206]". However, the data fold currently is empty.

It would be appreciated if the data can be posted at synapse. 

Best wishes,
Ting

**Comment by ricardovialle** [comment]
Dear Ting, 

My sincere apologies, we had some delays to get the signatures for the Data Transfer Agreement (DTA). I'll check the status and get back to you. 

Best,
Ricardo

**Comment by jxcao98** [comment]
Hi Ricardo, I notice the fold is still empty. Did I miss anything?

**Comment by ricardovialle** [comment]
Hi @jxcao98, 

I'm sorry about that; we still didn't resolve the issue with Synapse. Alternatives for accessing the data are via NIAGADS (https://dss.niagads.org/datasets/ng00118/) or at the RADC Hub (ROSMAP only; https://www.radc.rush.edu/).
Please let me know if you need further assistance. 

Best,
Ricardo
