### ISSUE TITLE
Number of callers in SURVIVOR merge tools for DEL

### ISSUE THREAD

**Issue by olivia-gc** [RajLabMSSM/AMP_AD_StructuralVariation#3]
Hi, I just wanted some clarification on the 'merge tools' step for DEL in the pipeline. From my understanding DEL calls should overlap between be manta AND 2 callers? Or manta OR 2 callers? 

I am trying to follow the pipeline, and from my understanding we call upon the SURVIVOR merge in the merge_and_benchmark_vcfs_truvari.sh script to merge the DEL tools. I am confused because in this script, there is SURVIVOR with min_num_calls=1. Any clarification would be very appreciated. 

Thank you

**Comment by ricardovialle** [comment]
Hi, 
Sorry, I missed your question. 
The rule was all Manta calls plus any other deletion found by at least 2 other tools. 
Please let me know if you still need assistance. 

Best,
Ricardo
