### ISSUE TITLE
how to get the case ID for each SV

### ISSUE THREAD

**Issue by BenxiaHu** [RajLabMSSM/AMP_AD_StructuralVariation#4]
Hello,
   Thanks for generating this great SV resources. 
   I just check the VCF files for SVs deposited in this github (https://github.com/RajLabMSSM/AMP_AD_StructuralVariation/tree/main/data/SV_calls). Thanks a lot.
   I wan to know which SV comes from individual with diease or not.

  for example,
<img width="828" alt="image" src="https://github.com/user-attachments/assets/c05dc58f-7c6c-476d-a2b8-06be9e29562a">

I wan to know whether this SV is from AD or normal brain.

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>

id | rosmap | mayo | msbb | chrom | pos | sv_end | svlen | alt
-- | -- | -- | -- | -- | -- | -- | -- | --
DEL_9591 | DEL_20772 | DEL_12918 | DEL_14777 | 3 | 184125375 | 184125569 | -199 | <DEL>

</body>

</html>

  Would you like to provide a metafile explaining each SV from different individual with disease or not.

<img width="1213" alt="image" src="https://github.com/user-attachments/assets/6eb6cf30-fab5-4bbf-baf8-6c21b3e8065b">

https://dss.niagads.org/sample-sets/snd10041/

Best

**Comment by ricardovialle** [comment]
Hi, 
Thanks for reaching out. 
I could provide the total number of cases/controls for each SV, but I can't share the individual-level information publicly. That data should be available via NIAGADS (or ROSMAP only, via separate request at https://www.radc.rush.edu/)

Please let me know if the summarized numbers would help you. 

Best,
Ricardo

**Comment by BenxiaHu** [comment]
Hello Ricardo,
thanks for sharing.
I do not need the individual information.
I just want to know which SV is from AD or normal sample.
for example,
deletion1 Normal
deletion2 AD
deletion3 Normal/AD

**Comment by ricardovialle** [comment]
Hi @BenxiaHu,
Unfortunately, this is not something I can say. These SVs are shared in disease and controls. It might happen that some SVs are a little more frequent in one group than the other; this is what the association result is trying to show. 

You can get this information (e.g. the SV is more likely to happen in AD) by checking the p-values and slopes from the results here: https://github.com/RajLabMSSM/AMP_AD_StructuralVariation/tree/main/data/disease_associations

Also, if you are interested, I just released another set of results of associations for several clinical and pathological AD-related traits. Using the same SVs detected here (ROSMAP only). You can find the results here: https://github.com/RushAlz/ADRD_SV_GWAS 

Best,
Ricardo

**Comment by BenxiaHu** [comment]
Hello Ricardo,

Thanks a lot.

These files are really helpful.

So this file, ROSMAP_meta_analysis_results.tsv.gz, just contain SVs only detected in AD patients, right?

Would you like to share your e-mail address? I can directly e-mail you if I have any other questions.
Best,

Benxia

**Comment by ricardovialle** [comment]
Hi, 

Yes, most SVs will be found in at least one person with AD (not necessarily linked to the disease). These are all common allele frequency variants. 
You can reach me at ricardo_a_vialle[at]rush[dot]edu

Best,
Ricardo
